### ISSUE TITLE
Шприц (3d-модель)

### ISSUE THREAD

**Issue by KroTNR** [FreedomBay/techdemo#12]
### Требования
- Текстуры в виде одного сета 256x256
  - Albedo
  - Metallic Smoothness
- Полигонов (треугольников) <= 500
### Референсы
![image](https://user-images.githubusercontent.com/52551883/75629849-afef4f00-5bf6-11ea-8c04-e8649eef3fcc.png)

**Comment by IvanBadikov** [comment]
<img width="1532" alt="Screenshot 2020-03-12 at 23 06 34" src="https://user-images.githubusercontent.com/29948205/76565722-43a90100-64bc-11ea-8d2c-a30eb7042b35.png">
