### ISSUE TITLE
Комнаты

### ISSUE THREAD

**Issue by KroTNR** [FreedomBay/techdemo#6]
Комнаты - элементы локации, которые никуда не ведут. То есть, вход же и является выходом, а сама комната - тупиком. В комнатах

**Comment by IvanBadikov** [comment]
Таск выполнен по пунктам ТЗ 1 и 2:
https://docs.google.com/document/d/1J-w7o-J9GEEM1RxtzGHk_LRm77UA_qgJoVUvUNUHiWs/edit?usp=sharing
